export interface BibleBook {
  name: string;
  nameEn: string;
  chapters: number;
  category: string;
  summary: string;
  keyVerse: string;
  keyTheme: string;
  icon: string;
}

export interface BibleCategory {
  id: string;
  name: string;
  nameEn: string;
  testament: "old" | "new";
  color: string;
  gradient: string;
  description: string;
  image: string;
  books: BibleBook[];
}

export const bibleCategories: BibleCategory[] = [
  {
    id: "pentateuch",
    name: "모세오경",
    nameEn: "Pentateuch",
    testament: "old",
    color: "#D4A574",
    gradient: "from-amber-700 to-amber-900",
    description: "세계의 창조부터 이스라엘 민족의 형성까지, 하나님께서 인류와 맺으신 언약의 시작을 담고 있습니다.",
    image: "/bible-images/pentateuch.jpg",
    books: [
      {
        name: "창세기",
        nameEn: "Genesis",
        chapters: 50,
        category: "pentateuch",
        summary: "천지창조, 인류의 타락, 노아 홍수, 아브라함과의 언약, 이삭과 야곱의 이야기를 통해 하나님의 구원 계획이 시작됩니다. 죄로 인해 깨어진 세상 속에서 한 민족을 택하시어 온 인류를 구원하시겠다는 하나님의 약속이 흐릅니다.",
        keyVerse: "내가 너로 큰 민족을 이루고 네게 복을 주어 네 이름을 창대하게 하리니 너는 복의 근원이 될지라 (창 12:2)",
        keyTheme: "시작과 언약",
        icon: "🌅",
      },
      {
        name: "출애굽기",
        nameEn: "Exodus",
        chapters: 40,
        category: "pentateuch",
        summary: "430년간의 애굽 노예 생활에서 이스라엘을 구원하시는 하나님의 권능을 보여줍니다. 모세를 통해 열 재앙을 내리시고 홍해를 가르시며, 시내산에서 십계명과 언약을 주십니다. 구속과 율법의 책입니다.",
        keyVerse: "내가 애굽 사람에게 어떻게 행함과 같이 내가 너희 위에 날개를 펴서 너희를 나의 품에 데려왔음을 너희가 보았으며 (출 19:4)",
        keyTheme: "구속과 해방",
        icon: "⛓️",
      },
      {
        name: "레위기",
        nameEn: "Leviticus",
        chapters: 27,
        category: "pentateuch",
        summary: "거룩하신 하나님과 죄인 사이의 교제를 가능케 하는 제사 제도와 정결 법을 다룹니다. 번제, 소제, 화목제, 속죄제, 속건제의 다섯 제사와 제사장의 직무를 규정하며, '거룩하라'는 부름이 핵심입니다.",
        keyVerse: "너희는 거룩하라 나 여호와 너희 하나님이 거룩함이니라 (레 19:2)",
        keyTheme: "거룩과 제사",
        icon: "🕯️",
      },
      {
        name: "민수기",
        nameEn: "Numbers",
        chapters: 36,
        category: "pentateuch",
        summary: "이스라엘의 광야 40년 방랑을 기록합니다. 두 차례의 인구 조사, 불평과 반역, 가데스바네아에서의 실패, 그럼에도 은혜를 베푸시는 하나님의 인내가 나타납니다. 숫자로 시작하지만 믿음의 여정을 보여줍니다.",
        keyVerse: "여호와는 그의 얼굴을 네게서 돌이키지 아니하시고 네게 평강을 주시기를 원하노라 (민 6:26)",
        keyTheme: "광야와 인내",
        icon: "🏜️",
      },
      {
        name: "신명기",
        nameEn: "Deuteronomy",
        chapters: 34,
        category: "pentateuch",
        summary: "모세의 마지막 설교로, 출애굽 세대가 광야에서 죽은 후 새 세대에게 율법을 다시 해설합니다. 과거를 회상하고, 십계명을 재천명하며, 축복과 저주를 선포합니다. 하나님을 온전히 사랑하라는 '쉐마'가 핵심입니다.",
        keyVerse: "이스라엘아 들으라 우리 하나님 여호와는 오직 하나인 여호와이시니 너는 마음을 다하고 뜻을 다하고 힘을 다하여 네 하나님 여호와를 사랑하라 (신 6:4-5)",
        keyTheme: "언약 갱신과 사랑",
        icon: "📜",
      },
    ],
  },
  {
    id: "historical-ot",
    name: "역사서",
    nameEn: "Historical Books",
    testament: "old",
    color: "#8B6914",
    gradient: "from-yellow-700 to-yellow-900",
    description: "가나안 정복부터 바벨론 포로 귀환까지, 이스라엘 민족의 흥망성쇠를 통해 하나님의 주권과 신실하심을 보여줍니다.",
    image: "/bible-images/historical.jpg",
    books: [
      {
        name: "여호수아",
        nameEn: "Joshua",
        chapters: 24,
        category: "historical-ot",
        summary: "모세의 후계자 여호수아가 이스라엘을 이끌고 가나안을 정복합니다. 여리고 함락, 중부·남부·북부 전역의 승리, 땅의 분배가 기록됩니다. 순종하는 자에게 승리를 주시는 하나님을 보여줍니다.",
        keyVerse: "오직 나와 내 집은 여호와를 섬기겠노라 (수 24:15)",
        keyTheme: "정복과 순종",
        icon: "⚔️",
      },
      {
        name: "사사기",
        nameEn: "Judges",
        chapters: 21,
        category: "historical-ot",
        summary: "가나안 정착 후 이스라엘이 죄를 짓고, 적국의 압제를 받으며, 사사를 통해 구원받는 패턴이 반복됩니다. 삼손, 기드온, 드보라 등의 사사 이야기를 통해 타락과 회복의 사이클을 보여줍니다.",
        keyVerse: "그 때에 이스라엘에 왕이 없으므로 사람이 각각 자기의 소견에 옳은 대로 행하였더라 (삿 21:25)",
        keyTheme: "타락과 회복의 반복",
        icon: "🔄",
      },
      {
        name: "룻기",
        nameEn: "Ruth",
        chapters: 4,
        category: "historical-ot",
        summary: "모압 여인 룻이 시어머니 나오미를 따라 베들레헴으로 돌아와 보아스와 결혼하는 아름다운 이야기입니다. 이방인도 하나님의 은혜 안에 들어올 수 있음을 보여주며, 다윗의 조상이 되어 메시아 계보에 포함됩니다.",
        keyVerse: "어머니가 가시는 곳에 나도 가고 어머니가 머무시는 곳에서 나도 머물겠나이다 (룻 1:16)",
        keyTheme: "은혜와 구속",
        icon: "🌾",
      },
      {
        name: "사무엘상",
        nameEn: "1 Samuel",
        chapters: 31,
        category: "historical-ot",
        summary: "사사 시대에서 왕정 시대로의 전환을 기록합니다. 사무엘의 출생과 사역, 사울의 등장과 타락, 다윗의 선택과 사울의 박해가 펼쳐집니다. 사람이 보는 외모가 아니라 중심을 보시는 하나님을 보여줍니다.",
        keyVerse: "사람은 외모를 보거니와 나 여호와는 중심을 보느니라 (삼상 16:7)",
        keyTheme: "왕정의 시작",
        icon: "👑",
      },
      {
        name: "사무엘하",
        nameEn: "2 Samuel",
        chapters: 24,
        category: "historical-ot",
        summary: "다윗의 통치 전성기와 위기를 다룹니다. 예루살렘 정복, 다윗 언약, 밧세바 사건, 압살롬의 반역 등이 기록됩니다. 죄를 지은 다윗이 회개할 때 용서하시지만 징계도 내리시는 하나님의 공의와 은혜가 나타납니다.",
        keyVerse: "내가 주께 범죄하였나이다 하니 나단이 다윗에게 이르되 여호와께서도 당신의 죄를 사하셨나니 (삼하 12:13)",
        keyTheme: "다윗 왕국의 영광과 위기",
        icon: "🏛️",
      },
      {
        name: "열왕기상",
        nameEn: "1 Kings",
        chapters: 22,
        category: "historical-ot",
        summary: "솔로몬의 영광스러운 통치와 성전 건축, 그 후 왕국의 분열을 기록합니다. 지혜로 시작했던 솔로몬이 우상 숭배로 타락하자, 이스라엘은 남북으로 갈라집니다. 엘리야의 갈멜산 대결도 포함됩니다.",
        keyVerse: "네 하나님 여호와께서 네 가운데 계시니 그는 구원을 베푸실 전능자이시라 (습 3:17)",
        keyTheme: "영광에서 분열로",
        icon: "🏺",
      },
      {
        name: "열왕기하",
        nameEn: "2 Kings",
        chapters: 25,
        category: "historical-ot",
        summary: "분열된 남북 왕국의 멸망을 기록합니다. 엘리야의 승천, 엘리사의 사역, 이스라엘(북)의 앗수르 멸망, 유다(남)의 바벨론 멸망까지 이릅니다. 끊임없는 우상 숭배가 국가 멸망의 원인임을 보여줍니다.",
        keyVerse: "여호와께서 그의 종 선지자들을 통해 하신 말씀과 같이 되었더라 (왕하 24:2)",
        keyTheme: "왕국의 멸망",
        icon: "🔥",
      },
      {
        name: "역대상",
        nameEn: "1 Chronicles",
        chapters: 29,
        category: "historical-ot",
        summary: "아담부터 다윗까지의 족보로 시작하여, 다윗 왕국의 영적 유산을 강조합니다. 제사장과 레위인의 조직, 성전 예배의 준비가 상세히 기록됩니다. 포로 귀환 후 정체성을 재확립하는 목적을 가집니다.",
        keyVerse: "여호와여 위엄과 주권과 영광과 승리와 찬송이 다 주의 것이니 (대상 29:11)",
        keyTheme: "다윗 언약의 기억",
        icon: "📋",
      },
      {
        name: "역대하",
        nameEn: "2 Chronicles",
        chapters: 36,
        category: "historical-ot",
        summary: "솔로몬의 성전 건축부터 유다 왕국의 멸망까지를 기록하며, 남유다 왕들에게 초점을 맞춥니다. 여호사밧, 히스기야, 요시아 같은 개혁 왕들의 부흥과, 끝내 회개하지 않아 포로로 끌려가는 비극을 보여줍니다.",
        keyVerse: "내 이름으로 일컫는 내 백성이 그들의 악한 길에서 떠나 스스로 겸비하고 기도하여 내 얼굴을 구하면 (대하 7:14)",
        keyTheme: "성전과 부흥",
        icon: "🛕",
      },
      {
        name: "에스라",
        nameEn: "Ezra",
        chapters: 10,
        category: "historical-ot",
        summary: "바벨론 포로에서 귀환한 유대인들이 예루살렘 성전을 재건하는 과정을 기록합니다. 고레스 칙령으로 제1차 귀환, 성전 재건의 방해와 완공, 에스라의 영적 개혁이 포함됩니다. 말씀 회복의 중요성을 강조합니다.",
        keyVerse: "우리 하나님의 선한 손이 우리 위에 있으므로 (스 8:22)",
        keyTheme: "귀환과 재건",
        icon: "🏗️",
      },
      {
        name: "느헤미야",
        nameEn: "Nehemiah",
        chapters: 13,
        category: "historical-ot",
        summary: "바사 왕의 술관 느헤미야가 예루살렘 성벽을 52일 만에 재건하는 이야기입니다. 기도와 행동, 반대자들의 방해 극복, 사회 개혁, 안식일 준수 회복 등이 기록됩니다. 지도자의 헌신과 하나님의 도우심을 보여줍니다.",
        keyVerse: "우리 하나님이 우리를 위하여 싸우시리라 (느 4:20)",
        keyTheme: "성벽 재건과 개혁",
        icon: "🧱",
      },
      {
        name: "에스더",
        nameEn: "Esther",
        chapters: 10,
        category: "historical-ot",
        summary: "바사 왕궁의 유대인 왕비 에스더가 민족 멸절 위기에서 용기 있게 나서 구원하는 이야기입니다. 하나님의 이름은 직접 언급되지 않지만, 모든 상황 속에서 은밀히 역사하시는 하나님의 섭리가 돋보입니다.",
        keyVerse: "이때에 당신이 말하지 아니하면 유다인은 다른 데로 말미를 얻으려니와 당신과 당신의 아비 집은 멸망하리라 (에 4:14)",
        keyTheme: "섭리와 용기",
        icon: "👸",
      },
    ],
  },
  {
    id: "poetry",
    name: "시가서",
    nameEn: "Poetry & Wisdom",
    testament: "old",
    color: "#6B8E23",
    gradient: "from-emerald-700 to-emerald-900",
    description: "인간의 가장 깊은 감정과 지혜를 시와 노래로 표현합니다. 고난 속에서도 하나님을 신뢰하는 법을 가르칩니다.",
    image: "/bible-images/poetry.jpg",
    books: [
      {
        name: "욥기",
        nameEn: "Job",
        chapters: 42,
        category: "poetry",
        summary: "의인 욥이 하루아침에 모든 것을 잃고 극심한 고난을 겪으며 친구들과 고통의 의미를 논쟁합니다. 결국 하나님이 친히 나타나 말씀하시며, 욥은 자신의 무지를 깨닫고 하나님의 주권을 인정합니다. 고난의 신비를 다룹니다.",
        keyVerse: "내가 주께 대하여 귀로 듣던 것을 이제는 눈으로 봄이로이다 (욥 42:5)",
        keyTheme: "고난과 주권",
        icon: "😢",
      },
      {
        name: "시편",
        nameEn: "Psalms",
        chapters: 150,
        category: "poetry",
        summary: "150편의 시와 노래로 구성된 이스라엘의 찬양과 기도 모음집입니다. 찬양, 탄원, 감사, 회개, 왕의 시 등 다양한 장르가 담겨 있으며, 다윗이 가장 많은 시를 썼습니다. 인간의 모든 감정을 하나님 앞에 쏟아내는 모범을 보여줍니다.",
        keyVerse: "여호와는 나의 목자시니 내게 부족함이 없으리로다 (시 23:1)",
        keyTheme: "찬양과 기도",
        icon: "🎵",
      },
      {
        name: "잠언",
        nameEn: "Proverbs",
        chapters: 31,
        category: "poetry",
        summary: "솔로몬과 다른 지혜자들이 기록한 삶의 지혜와 교훈의 모음입니다. 여호와를 경외하는 것이 지혜의 시작임을 천명하며, 말씀, 재물, 인간관계, 게으름 등 일상의 구체적인 주제에 대해 실용적인 가르침을 줍니다.",
        keyVerse: "여호와를 경외하는 것이 지혜의 시작이요 거룩하신 자를 아는 것이 명철이니라 (잠 9:10)",
        keyTheme: "지혜와 실천",
        icon: "💡",
      },
      {
        name: "전도서",
        nameEn: "Ecclesiastes",
        chapters: 12,
        category: "poetry",
        summary: "솔로몬이 인생의 헛됨을 깊이 성찰하는 철학적 묵상입니다. '해 아래'의 모든 것은 헛되지만, 하나님을 경외하고 그분의 선물을 누리는 삶이 유일한 의미임을 결론짓습니다. 세상의 부조리 앞에서 믿음으로 사는 법을 가르칩니다.",
        keyVerse: "일의 결국을 다 들었으니 하나님을 경외하고 그의 명령을 지킬지라 (전 12:13)",
        keyTheme: "헛됨과 경외",
        icon: "🌅",
      },
      {
        name: "아가",
        nameEn: "Song of Solomon",
        chapters: 8,
        category: "poetry",
        summary: "솔로몬과 술람미 여인 사이의 사랑을 시적으로 표현한 노래입니다. 육체적·감정적 사랑의 아름다움을 거리낌 없이 노래하며, 하나님이 제정하신 결혼 사랑의 거룩함을 찬양합니다. 그리스도와 교회의 사랑을 예표하기도 합니다.",
        keyVerse: "사랑은 죽음처럼 강하니라 (아 8:6)",
        keyTheme: "사랑의 노래",
        icon: "🌹",
      },
    ],
  },
  {
    id: "major-prophets",
    name: "대선지서",
    nameEn: "Major Prophets",
    testament: "old",
    color: "#8B0000",
    gradient: "from-red-800 to-red-950",
    description: "이사야부터 다니엘까지, 이스라엘의 심판과 회복, 그리고 메시아의 오심에 대한 장대한 예언을 담고 있습니다.",
    image: "/bible-images/major-prophets.jpg",
    books: [
      {
        name: "이사야",
        nameEn: "Isaiah",
        chapters: 66,
        category: "major-prophets",
        summary: "구약의 복음이라 불리는 메시아 예언의 보고입니다. 1-39장은 이스라엘의 죄와 심판을, 40-66장은 위로와 구원을 선포합니다. 고난 받는 종, 임마누엘, 새 하늘과 새 땅 등 핵심 메시아 예언이 풍성하게 담겨 있습니다.",
        keyVerse: "그는 우리의 질고를 지고 우리의 슬픔을 당하였거늘 (사 53:4)",
        keyTheme: "심판과 메시아 소망",
        icon: "📢",
      },
      {
        name: "예레미야",
        nameEn: "Jeremiah",
        chapters: 52,
        category: "major-prophets",
        summary: "눈물의 선지자 예레미야가 유다의 멸망 직전 40년간 회개를 촉구합니다. 백성의 거절과 핍박 속에서도 끝까지 말씀을 전하며, 바벨론 포로가 70년 후 끝날 것과 새 언약을 약속합니다. 눈물 속의 희망의 책입니다.",
        keyVerse: "나 여호와가 말하노라 너희를 향한 나의 생각은 내가 아나니 재앙이 아니라 곧 평안이요 너희 장래에 소망을 주려 하는 생각이라 (렘 29:11)",
        keyTheme: "회개와 새 언약",
        icon: "😢",
      },
      {
        name: "예레미야 애가",
        nameEn: "Lamentations",
        chapters: 5,
        category: "major-prophets",
        summary: "예루살렘 함락 후 파괴된 성읍을 애가하는 시 모음입니다. 처참한 고통 속에서도 여호와의 긍휼과 자비가 새벽마다 새로움을 고백합니다. 가장 깊은 절망에서조차 하나님의 사랑을 붙잡는 믿음을 보여줍니다.",
        keyVerse: "여호와의 인자하심과 긍휼하심이 무궁하시므로 우리가 진멸되지 아니함이여 이것이 아침마다 새로우니 주의 성실하심이 크도소이다 (애 3:22-23)",
        keyTheme: "절망 속의 소망",
        icon: "💔",
      },
      {
        name: "에스겔",
        nameEn: "Ezekiel",
        chapters: 48,
        category: "major-prophets",
        summary: "바벨론 포로 중인 에스겔이 이스라엘의 영적 부흥을 예언합니다. 하나님의 영광이 성전을 떠나는 환상, 마른 뼈가 살아나는 환상, 새 성전 환상 등이 기록됩니다. 죽은 민족도 하나님이 살리실 수 있음을 보여줍니다.",
        keyVerse: "너희에게 새 마음을 주고 너희 속에 새 영을 넣되 (겔 36:26)",
        keyTheme: "영광과 부흥",
        icon: "💀",
      },
      {
        name: "다니엘",
        nameEn: "Daniel",
        chapters: 12,
        category: "major-prophets",
        summary: "바벨론 포로 중인 다니엘이 사자굴과 풀무불에서 구원받으며, 세계 제국의 흥망과 종말의 환상을 봅니다. 역사의 주관자이신 하나님이 이방 왕들 사이에서도 자기 백성을 지키시며, 마침내 영원한 나라를 세우실 것을 예언합니다.",
        keyVerse: "내 하나님이 그의 천사를 보내어 사자들의 입을 봉하셨으므로 (단 6:22)",
        keyTheme: "역사의 주관자",
        icon: "🦁",
      },
    ],
  },
  {
    id: "minor-prophets",
    name: "소선지서",
    nameEn: "Minor Prophets",
    testament: "old",
    color: "#9370DB",
    gradient: "from-purple-700 to-purple-900",
    description: "짧지만 강렬한 12선지자의 메시지가 사회 정의, 진정한 예배, 메시아 소망, 그리고 하나님의 사랑을 선포합니다.",
    image: "/bible-images/minor-prophets.jpg",
    books: [
      {
        name: "호세아",
        nameEn: "Hosea",
        chapters: 14,
        category: "minor-prophets",
        summary: "선지자 호세아가 음란한 아내 고멜을 다시 사랑하듯, 배반한 이스라엘을 끝까지 사랑하시는 하나님의 마음을 보여줍니다. 심판이 선포되지만 마지막은 회복과 사랑으로 끝납니다. 하나님의 질투하는 사랑이 핵심입니다.",
        keyVerse: "내가 무죄하게 하는 사랑으로 너를 사랑하였으므로 (호 14:4)",
        keyTheme: "질투하는 사랑",
        icon: "💔",
      },
      {
        name: "요엘",
        nameEn: "Joel",
        chapters: 3,
        category: "minor-prophets",
        summary: "메뚜기 재앙을 심판의 징조로 해석하며 회개를 촉구합니다. '만군의 여호와의 크고 두려운 날' 이전에 하나님의 영을 모든 육체에 부어주실 것을 약속합니다. 오순절 성령 강림의 예언적 근거가 됩니다.",
        keyVerse: "그 후에 내가 내 영을 만민에게 부어 주리니 (욜 2:28)",
        keyTheme: "성령과 심판",
        icon: "🦗",
      },
      {
        name: "아모스",
        nameEn: "Amos",
        chapters: 9,
        category: "minor-prophets",
        summary: "북이스라엘의 사회 부정의를 정죄하는 정의의 선지자입니다. 가난한 자를 억압하는 부자들, 형식적인 예배를 강력히 비판합니다. 사회 정의가 없는 예배는 하나님이 받지 않으시며, 정의를 강물처럼 흘리라 고발합니다.",
        keyVerse: "오직 공법을 물 같이 정의를 하수 같이 흘릴지로다 (암 5:24)",
        keyTheme: "정의와 공의",
        icon: "⚖️",
      },
      {
        name: "오바댜",
        nameEn: "Obadiah",
        chapters: 1,
        category: "minor-prophets",
        summary: "구약에서 가장 짧은 책으로, 이스라엘의 형제 국가 에돔이 유다의 멸망을 보고도 돕지 않은 죄를 정죄합니다. 교만한 자는 낮아지고, 여호와의 날에 모든 열방이 심판받을 것을 선포합니다.",
        keyVerse: "네가 행한 대로 너도 받을 것인즉 (옵 1:15)",
        keyTheme: "에돔의 심판",
        icon: "🏔️",
      },
      {
        name: "요나",
        nameEn: "Jonah",
        chapters: 4,
        category: "minor-prophets",
        summary: "하나님이 이방 도시 니느웨로 보내신 요나가 도망치다 큰 물고기 뱃속에서 회개합니다. 니느웨가 회개하자 요나는 분노하지만, 하나님은 모든 민족을 사랑하심을 보여주십니다. 하나님의 구원은 유대인에게만 국한되지 않습니다.",
        keyVerse: "구원은 여호와께로서 말미암나이다 (욘 2:9)",
        keyTheme: "이방인 구원과 하나님의 긍휼",
        icon: "🐋",
      },
      {
        name: "미가",
        nameEn: "Micah",
        chapters: 7,
        category: "minor-prophets",
        summary: "유다와 이스라엘의 죄를 정죄하며 베들레헴에서 태어날 메시아를 예언합니다. 하나님이 요구하시는 것은 제물이 아니라 공의를 행하며 인자를 사랑하며 겸손히 하나님과 함께 행하는 것임을 천명합니다.",
        keyVerse: "사람아 주께서 선한 것이 무엇임을 네게 보이셨나니 여호와께서 네게 구하시는 것은 오직 공의를 행하며 인자를 사랑하며 겸손히 네 하나님과 함께 행하는 것이 아니냐 (미 6:8)",
        keyTheme: "공의와 인자",
        icon: "🏘️",
      },
      {
        name: "나훔",
        nameEn: "Nahum",
        chapters: 3,
        category: "minor-prophets",
        summary: "앗수르 제국의 수도 니느웨의 멸망을 선포합니다. 요나 시절 회개했던 니느웨가 다시 포악해져 마침내 심판을 받습니다. 하나님은 노하기를 더디 하시고 권능이 크시며, 죄인을 결코 벌하지 않으시는 분이 아니심을 보여줍니다.",
        keyVerse: "여호와는 노하기를 더디하시나 권능이 크시사 벌하지 아니하지 아니하시느니라 (나 1:3)",
        keyTheme: "니느웨의 멸망",
        icon: "⚡",
      },
      {
        name: "하박국",
        nameEn: "Habakkuk",
        chapters: 3,
        category: "minor-prophets",
        summary: "의인이 왜 고난받고 악인이 형통한지 하나님께 질문하는 선지자의 대화입니다. 하나님은 바벨론을 심판 도구로 쓰시지만 그들도 심판하실 것이라 답하십니다. 의인은 믿음으로 살 것이라는 위대한 선언으로 마칩니다.",
        keyVerse: "의인은 그의 믿음으로 말미암아 살리라 (합 2:4)",
        keyTheme: "믿음으로 살라",
        icon: "❓",
      },
      {
        name: "스바냐",
        nameEn: "Zephaniah",
        chapters: 3,
        category: "minor-prophets",
        summary: "여호와의 날, 곧 심판의 날이 임박했음을 선포합니다. 유다의 우상 숭배와 교만을 정죄하며, 온 땅의 심판을 예고합니다. 그러나 남은 자에게는 구원과 기쁨을 약속하며, 하나님이 함께하시는 백성의 노래로 끝납니다.",
        keyVerse: "너는 두려워하지 말라 시온아 네 손을 늘어뜨리지 말라 (습 3:16)",
        keyTheme: "여호와의 날",
        icon: "🌩️",
      },
      {
        name: "학개",
        nameEn: "Haggai",
        chapters: 2,
        category: "minor-prophets",
        summary: "포로 귀환 후 성전 재건을 게을리하는 백성을 촉구합니다. 자기 집은 지으면서 하나님의 집은 폐허로 방치한 것을 정죄하며, 성전을 건축하면 하나님이 영광으로 채우시리라 약속합니다. 우선순위의 회복을 촉구합니다.",
        keyVerse: "이 전의 나중 영광이 이전 영광보다 크리라 (학 2:9)",
        keyTheme: "성전 재건 촉구",
        icon: "🔨",
      },
      {
        name: "스가랴",
        nameEn: "Zechariah",
        chapters: 14,
        category: "minor-prophets",
        summary: "학개와 함께 성전 재건을 격려하며, 메시아 예언이 풍성한 책입니다. 승마한 자의 환상, 감람나무 환상, 의인으로 오시는 왕, 찔린 자, 등 메시아적 이미지가 많습니다. 은혜를 구하라는 부르심이 반복됩니다.",
        keyVerse: "만군의 여호와가 말하노라 너희는 돌이키라 나도 돌이키리라 (슥 1:3)",
        keyTheme: "메시아 예언과 위로",
        icon: "🌿",
      },
      {
        name: "말라기",
        nameEn: "Malachi",
        chapters: 4,
        category: "minor-prophets",
        summary: "구약의 마지막 책으로, 백성의 형식적인 예배와 결혼의 거룩함 상실, 십일조 무시를 책망합니다. 의로운 해가 뜨는 날, 엘리야를 보내시겠다는 약속으로 구약을 마칩니다. 400년의 침묵 전 마지막 하나님의 음성입니다.",
        keyVerse: "내가 너희를 사랑하였노라 (말 1:2)",
        keyTheme: "사랑과 심판",
        icon: "☀️",
      },
    ],
  },
  {
    id: "gospels",
    name: "복음서",
    nameEn: "Gospels",
    testament: "new",
    color: "#4169E1",
    gradient: "from-sky-700 to-sky-900",
    description: "예수 그리스도의 탄생, 사역, 십자가 죽음, 부활을 네 가지 관점에서 증언합니다. 하나님이 사람이 되셔서 우리를 구원하신 가장 복된 소식입니다.",
    image: "/bible-images/gospels.jpg",
    books: [
      {
        name: "마태복음",
        nameEn: "Matthew",
        chapters: 28,
        category: "gospels",
        summary: "유대인을 향해 쓰여, 예수님이 구약이 약속한 메시아이심을 증명합니다. 다윗의 자손으로서의 족보, 산상수훈, 천국 비유, 그리고 '내가 너희에게 분부한 모든 것을 가르쳐 지키게 하라'는 대사명으로 마칩니다. 왕으로서의 예수님이 강조됩니다.",
        keyVerse: "그러므로 너희는 가서 모든 민족을 제자로 삼아 아버지와 아들과 성령의 이름으로 세례를 베풀고 (마 28:19)",
        keyTheme: "왕 메시아",
        icon: "👑",
      },
      {
        name: "마가복음",
        nameEn: "Mark",
        chapters: 16,
        category: "gospels",
        summary: "가장 짧고 역동적인 복음서로, 예수님의 행동과 능력을 빠른 속도로 전합니다. '즉시', '곧' 같은 표현이 반복되며, 종으로서의 예수님이 강조됩니다. 섬기러 오신 하나님의 아들의 사역이 생생하게 기록됩니다.",
        keyVerse: "인자가 온 것은 섬김을 받으려 함이 아니라 도리어 섬기려 하고 자기 목숨을 많은 사람의 대속물로 주려 함이니라 (막 10:45)",
        keyTheme: "섬기는 종",
        icon: "🏃",
      },
      {
        name: "누가복음",
        nameEn: "Luke",
        chapters: 24,
        category: "gospels",
        summary: "의사 누가가 정확한 조사를 바탕으로 기록한 복음서로, 소외된 자, 여성, 이방인, 세리와 죄인에게 향하신 예수님의 긍휼을 강조합니다. 잃어버린 양, 잃어버린 드라크마, 탕자의 비유 등 은혜의 이야기가 풍성합니다.",
        keyVerse: "인자의 온 것은 잃어버린 자를 찾아 구원하려 함이니라 (눅 19:10)",
        keyTheme: "구원자의 긍휼",
        icon: "🩺",
      },
      {
        name: "요한복음",
        nameEn: "John",
        chapters: 21,
        category: "gospels",
        summary: "가장 영적이고 신학적인 복음서로, 예수님이 하나님의 아들이심을 믿음으로 영생을 얻게 하려고 기록되었습니다. '나는 ~이다' 선언, 영생, 거룩한 성만차, 보혜사 약속 등이 담겨 있으며, 사랑의 제자가 쓴 믿음의 고백입니다.",
        keyVerse: "하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 이는 그를 믿는 자마다 멸망하지 않고 영생을 얻게 하려 하심이라 (요 3:16)",
        keyTheme: "하나님의 아들과 영생",
        icon: "🕊️",
      },
    ],
  },
  {
    id: "acts",
    name: "역사서",
    nameEn: "Acts",
    testament: "new",
    color: "#FF6347",
    gradient: "from-orange-600 to-orange-800",
    description: "예수님 승천 후 성령 강림으로 교회가 탄생하고, 복음이 예루살렘에서 로마까지 전파되는 초대 교회의 역사입니다.",
    image: "/bible-images/acts.jpg",
    books: [
      {
        name: "사도행전",
        nameEn: "Acts",
        chapters: 28,
        category: "acts",
        summary: "성령 강림으로 교회가 탄생하고, 복음이 유대에서 사마리아, 온 세계로 퍼져나가는 역동적인 기록입니다. 베드로의 설교, 스데반의 순교, 바울의 회심과 선교 여행, 로마까지의 복음 전파가 담겨 있습니다. 성령의 책입니다.",
        keyVerse: "오직 성령이 너희에게 임하시면 너희가 권능을 받고 예루살렘과 온 유대와 사마리아와 땅끝까지 이르러 내 증인이 되리라 (행 1:8)",
        keyTheme: "성령과 교회 확장",
        icon: "🔥",
      },
    ],
  },
  {
    id: "pauline-epistles",
    name: "바울 서신",
    nameEn: "Pauline Epistles",
    testament: "new",
    color: "#2E8B57",
    gradient: "from-teal-700 to-teal-900",
    description: "사도 바울이 교회들에게 쓴 편지들로, 복음의 핵심 교리, 믿음으로 말미암는 의, 그리고 성도의 실천적 삶을 깊이 있게 가르칩니다.",
    image: "/bible-images/pauline.jpg",
    books: [
      {
        name: "로마서",
        nameEn: "Romans",
        chapters: 16,
        category: "pauline-epistles",
        summary: "바울의 신학적 대작으로, 모든 사람이 죄인이며 오직 믿음으로 의롭다 함을 받는다는 복음의 핵심을 체계적으로 전개합니다. 유대인과 이방인의 구원, 율법과 은혜, 성화의 삶, 하나님의 주권적 선택을 다룹니다. 종교개혁의 기폭제였던 책입니다.",
        keyVerse: "그러므로 우리가 믿음으로 의롭다 하심을 받았으니 우리 주 예수 그리스도로 말미암아 하나님과 화평을 누리자 (롬 5:1)",
        keyTheme: "이신칭의와 복음",
        icon: "📖",
      },
      {
        name: "고린도전서",
        nameEn: "1 Corinthians",
        chapters: 16,
        category: "pauline-epistles",
        summary: "분쟁과 혼란이 가득한 고린도 교회에 바울이 문제를 지적하고 해답을 줍니다. 파벌주의, 성적 부도덕, 소송, 성만차, 은사 문제, 부활 교리 등을 다루며, 무엇보다 사랑장(13장)으로 모든 문제의 해답이 사랑임을 보여줍니다.",
        keyVerse: "그런즉 믿음, 소망, 사랑 이 세 가지는 항상 있을 것인데 그중의 제일은 사랑이라 (고전 13:13)",
        keyTheme: "교회 문제와 사랑",
        icon: "❤️",
      },
      {
        name: "고린도후서",
        nameEn: "2 Corinthians",
        chapters: 13,
        category: "pauline-epistles",
        summary: "바울의 가장 개인적이고 감정적인 편지입니다. 사도권을 의심하는 자들에게 변호하며, 고난 속에서도 위로를 주시는 하나님을 증언합니다. 약함 속에서 강함이 나타나는 역설적 복음을 보여주며, 옛 자신과 새 피조물의 대비를 선포합니다.",
        keyVerse: "내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라 (고후 12:9)",
        keyTheme: "약함 속의 강함",
        icon: "🛡️",
      },
      {
        name: "갈라디아서",
        nameEn: "Galatians",
        chapters: 6,
        category: "pauline-epistles",
        summary: "율법으로 돌아가려는 갈라디아 교인들에게 믿음만으로 구원받음을 강력히 변호합니다. 율법의 저주에서 그리스도가 구속하셨으며, 할례나 무할례가 아니라 사랑으로 역사하는 믿음만이 중요함을 선포합니다. 기독교 자유의 헌장입니다.",
        keyVerse: "그리스도께서 우리를 자유롭게 하려고 자유를 주셨으니 그러므로 굳건하게 서서 다시는 종의 멍에를 메지 말라 (갈 5:1)",
        keyTheme: "믿음과 자유",
        icon: "⛓️",
      },
      {
        name: "에베소서",
        nameEn: "Ephesians",
        chapters: 6,
        category: "pauline-epistles",
        summary: "교회의 영광스러운 정체성과 성도의 실천적 삶을 조화롭게 다룹니다. 1-3장은 하나님의 풍성한 은혜와 교회의 신비를, 4-6장은 이에 합당한 삶, 곧 하나 됨, 빛의 자녀, 성령 충만, 영적 전투를 가르칩니다.",
        keyVerse: "너희가 은혜로 말미암아 믿음으로 말미암아 구원을 받았으니 이것은 너희에게서 난 것이 아니요 하나님의 선물이라 (엡 2:8)",
        keyTheme: "은혜와 교회",
        icon: "💒",
      },
      {
        name: "빌립보서",
        nameEn: "Philippians",
        chapters: 4,
        category: "pauline-epistles",
        summary: "감옥에서 쓴 편지이지만 가장 기쁨이 넘치는 서신입니다. 빌립보 교회의 사랑에 감사하며, 모든 일에 자족하는 비결, 자기의 유익을 버리시고 낮아지신 그리스도의 겸손을 본받으라 권면합니다. 기쁨의 서신입니다.",
        keyVerse: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라 (빌 4:13)",
        keyTheme: "기쁨과 겸손",
        icon: "😊",
      },
      {
        name: "골로새서",
        nameEn: "Colossians",
        chapters: 4,
        category: "pauline-epistles",
        summary: "그리스도의 충만성과 절대적 우월성을 강조하며, 이단 사상을 물리칩니다. 모든 지혜와 지식의 보장이 그리스도 안에 있으며, 우주적 주권자이신 그리스도만이 구원의 전부이심을 선포합니다. 그리스도 중심의 책입니다.",
        keyVerse: "그 안에는 신성의 모든 충만이 육체로 거하시고 (골 2:9)",
        keyTheme: "그리스도의 충만성",
        icon: "✨",
      },
      {
        name: "데살로니가전서",
        nameEn: "1 Thessalonians",
        chapters: 5,
        category: "pauline-epistles",
        summary: "바울의 첫 서신으로, 핍박 중에도 믿음을 지키는 데살로니가 교회를 칭찬합니다. 죽은 성도의 부활과 주의 재림을 가르치며, 깨어 근신하며 믿음과 사랑과 소망의 전신 갑주를 입으라 권면합니다.",
        keyVerse: "항상 기뻐하라 쉬지 말고 기도하라 범사에 감사하라 (살전 5:16-18)",
        keyTheme: "재림 소망과 깨어 있음",
        icon: "⏰",
      },
      {
        name: "데살로니가후서",
        nameEn: "2 Thessalonians",
        chapters: 3,
        category: "pauline-epistles",
        summary: "주의 날이 이미 이르렀다는 잘못된 가르침을 바로잡습니다. 배도하는 자와 불법의 사람이 나타나기 전에 주의 날은 오지 않음을 설명하며, 성도를 견고하게 하시고 악한 자에게서 지켜주시기를 기도합니다.",
        keyVerse: "주는 미쁘시니 너희를 굳게 하시고 악한 자에게서 지키시리라 (살후 3:3)",
        keyTheme: "재림 징조와 견고함",
        icon: "🛡️",
      },
      {
        name: "디모데전서",
        nameEn: "1 Timothy",
        chapters: 6,
        category: "pauline-epistles",
        summary: "바울이 젊은 목회자 디모데에게 보내는 교회 지침서입니다. 거짓 교사 경계, 예배의 질서, 감독과 집사의 자격, 권면하는 자세, 재물에 대한 태도 등 교회 운영의 실제적 지침을 제공합니다. 목회 서신의 하나입니다.",
        keyVerse: "믿음의 싸움을 싸우고 영생을 취하라 (딤전 6:12)",
        keyTheme: "교회 질서와 목회 지침",
        icon: "📋",
      },
      {
        name: "디모데후서",
        nameEn: "2 Timothy",
        chapters: 4,
        category: "pauline-epistles",
        summary: "바울의 마지막 편지로, 순교를 앞두고 디모데에게 믿음을 지키라 당부합니다. 말씀을 전파하라, 고난을 받으라, 충성하라는 유언적 권면이 감동적으로 기록됩니다. '내가 선한 싸움을 싸우고'라는 고백이 핵심입니다.",
        keyVerse: "내가 선한 싸움을 싸우고 나의 달려갈 길을 마치고 믿음을 지켰으니 (딤후 4:7)",
        keyTheme: "끝까지 충성하라",
        icon: "⚔️",
      },
      {
        name: "디도서",
        nameEn: "Titus",
        chapters: 3,
        category: "pauline-epistles",
        summary: "크레데 교회를 돌보는 디도에게 보낸 목회 지침입니다. 장로의 자격, 건전한 교훈, 성도의 삶의 실천, 은혜의 복음이 경건한 삶으로 열매 맺어야 함을 강조합니다. 바울 서신의 교리와 실천의 조화를 잘 보여줍니다.",
        keyVerse: "우리 구주 하나님의 자비와 사람 사랑하심을 나타내실 때에 (딛 3:4)",
        keyTheme: "건전한 교훈과 경건",
        icon: "📝",
      },
      {
        name: "빌레몬서",
        nameEn: "Philemon",
        chapters: 1,
        category: "pauline-epistles",
        summary: "도주한 종 오네시모를 주인 빌레몬에게 보내며 용서를 구하는 개인적 편지입니다. 그리스도 안에서의 형제 사랑이 사회적 신분을 초월함을 보여줍니다. 바울의 따뜻한 인격과 복음이 인간 관계를 어떻게 변화시키는지 감동적으로 담겨 있습니다.",
        keyVerse: "이후로는 종과 같이 아니하고 종보다 더 사랑하는 형제로 여기라 (몬 1:16)",
        keyTheme: "용서와 형제 사랑",
        icon: "🤝",
      },
    ],
  },
  {
    id: "general-epistles",
    name: "공동 서신",
    nameEn: "General Epistles",
    testament: "new",
    color: "#CD853F",
    gradient: "from-amber-600 to-amber-800",
    description: "바울 외의 사도들이 쓴 편지들로, 고난 속의 인내, 믿음과 행함, 거룩한 삶, 사랑의 실천 등 성도의 삶을 다각도로 권면합니다.",
    image: "/bible-images/general-epistles.jpg",
    books: [
      {
        name: "히브리서",
        nameEn: "Hebrews",
        chapters: 13,
        category: "general-epistles",
        summary: "옛 언약의 모든 것이 그리스도 안에서 성취되었음을 논증합니다. 천사보다, 모세보다, 아론보다 뛰어나신 그리스도, 온전하고 영원한 대제사장이신 그리스도를 증언하며, 믿음으로 살라 강력히 권면합니다. 믿음 장(11장)이 유명합니다.",
        keyVerse: "믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니 (히 11:1)",
        keyTheme: "그리스도의 우월성과 믿음",
        icon: "🏔️",
      },
      {
        name: "야고보서",
        nameEn: "James",
        chapters: 5,
        category: "general-epistles",
        summary: "믿음은 행함으로 온전해진다고 가르치는 실천적 서신입니다. 시련을 기쁨으로 여기라, 들을 뿐 아니라 행하라, 혀를 제어하라, 편견을 버리라, 병든 자를 위해 기도하라 등 구체적이고 실천적인 권면이 특징입니다. 행동하는 믿음을 강조합니다.",
        keyVerse: "영혼 없는 믿음이 죽은 것 같이 행함이 없는 믿음은 죽은 것이니라 (약 2:26)",
        keyTheme: "행함 있는 믿음",
        icon: "🔨",
      },
      {
        name: "베드로전서",
        nameEn: "1 Peter",
        chapters: 5,
        category: "general-epistles",
        summary: "합박을 받는 소아시아 성도들에게 고난 중에서도 소망을 잃지 말라 권면합니다. 선택받은 나그네로서 거룩한 삶, 그리스도의 본을 받는 고난, 섬기는 지도자의 자세를 가르치며, 고난은 성도를 정결하게 만드는 도구임을 보여줍니다.",
        keyVerse: "너희를 부르사 그의 영광과 덕으로써 보이신 이를 우리가 더욱 힘써 알라 (벧후 1:10은 후서, 전서 핵심구절: 너희 염려를 다 주께 맡겨 버리라 이는 주가 너희를 돌보심이라 - 벧전 5:7)",
        keyTheme: "고난 중의 소망",
        icon: "⚓",
      },
      {
        name: "베드로후서",
        nameEn: "2 Peter",
        chapters: 3,
        category: "general-epistles",
        summary: "거짓 선지자와 이단을 경계하며, 믿음에 덕을, 덕에 지식을 더하라 권면합니다. 주의 강림이 더딘 것은 아무도 멸망하지 않고 다 회개하기를 바라시는 하나님의 인내 때문임을 설명하며, 거룩함과 경건함으로 주의 날을 기다리라 합니다.",
        keyVerse: "주의 약속은 어떤 이들이 더딘 것으로 생각하나 더딘이 아니라 오직 너희에 대하여 오래 참으사 아무도 멸망하지 않고 다 회개하기에 이르기를 원하시느니라 (벧후 3:9)",
        keyTheme: "거짓 교훈과 재림",
        icon: "⚠️",
      },
      {
        name: "요한일서",
        nameEn: "1 John",
        chapters: 5,
        category: "general-epistles",
        summary: "하나님은 사랑이시라는 위대한 진리를 선포하며, 빛 가운데 행하라, 서로 사랑하라, 영들을 시험하라 권면합니다. 하나님의 자녀와 마귀의 자녀를 구별하는 기준은 사랑과 의의 실천이며, 영생을 확신할 수 있음을 보증합니다.",
        keyVerse: "사랑은 여기 있으니 우리가 하나님을 사랑한 것이 아니요 하나님이 우리를 사랑하사 (요일 4:10)",
        keyTheme: "사랑과 확신",
        icon: "❤️",
      },
      {
        name: "요한이서",
        nameEn: "2 John",
        chapters: 1,
        category: "general-epistles",
        summary: "선택받은 부녀에게 보낸 짧은 편지로, 서로 사랑하라는 계명과 그리스도께 육체로 오심을 부인하는 적그리스도를 경계하라는 두 가지 권면을 담습니다. 사랑과 진리의 균형을 유지할 것을 당부합니다.",
        keyVerse: "서로 사랑하자 이것은 처음부터 우리가 들은 명령이요 (요이 1:5)",
        keyTheme: "사랑과 진리",
        icon: "💌",
      },
      {
        name: "요한삼서",
        nameEn: "3 John",
        chapters: 1,
        category: "general-epistles",
        summary: "가이오에게 보낸 짧은 편지로, 진리 안에서 행하는 것을 기뻐하며, 선한 일을 행하는 데메드리오를 본받으라 권면합니다. 교회 내에서 선한 지도자와 악한 지도자(디오드레베)의 대비를 보여줍니다.",
        keyVerse: "사랑하는 자여 네 영혼이 잘 됨같이 네가 범사에 잘 되고 강건하기를 내가 간구하노라 (요삼 1:2)",
        keyTheme: "진리 안의 교제",
        icon: "✉️",
      },
      {
        name: "유다서",
        nameEn: "Jude",
        chapters: 1,
        category: "general-epistles",
        summary: "교회 안에 침투한 불경건한 자들을 강력히 정죄합니다. 은혜를 방종으로 바꾸는 자들, 권위를 멸시하는 자들을 경계하며, 믿음의 도를 굳게 지키고 긍휼과 두려움으로 불쌍히 여기라고 권면합니다. 영적 전투의 촉구입니다.",
        keyVerse: "사랑하는 자들아 너희가 우리 주 예수 그리스도의 사도들이 미리 한 말을 기억하라 (유 1:17)",
        keyTheme: "믿음 수호",
        icon: "🛡️",
      },
    ],
  },
  {
    id: "revelation",
    name: "예언서",
    nameEn: "Revelation",
    testament: "new",
    color: "#FFD700",
    gradient: "from-yellow-600 to-yellow-800",
    description: "성경의 마지막 책으로, 종말의 심판과 새 하늘과 새 땅의 영광을 계시합니다. 사탄의 최후 패배와 하나님 나라의 완성을 보여줍니다.",
    image: "/bible-images/revelation.jpg",
    books: [
      {
        name: "요한계시록",
        nameEn: "Revelation",
        chapters: 22,
        category: "revelation",
        summary: "사도 요한이 밧모 섬에서 본 종말의 계시입니다. 일곱 교회, 일곱 인, 일곱 나팔, 일곱 대접의 심판, 짐승과 바벨론의 멸망, 그리스도의 재림과 천년왕국, 새 하늘과 새 땅이 기록됩니다. 악이 최종 패배하고 하나님이 모든 것 안에 모든 것이 되시는 영광스러운 결말입니다.",
        keyVerse: "보라 하나님의 장막이 사람들과 함께 있으매 하나님이 그들과 함께 거하시리니 그들은 하나님의 백성이 되고 하나님은 친히 그들과 함께 계셔서 (계 21:3)",
        keyTheme: "종말과 새 창조",
        icon: "🌟",
      },
    ],
  },
];

export const testamentInfo = {
  old: {
    name: "구약성경",
    nameEn: "Old Testament",
    bookCount: 39,
    description: "천지창조부터 메시아 약속까지, 하나님의 언약과 구원 계획의 시작",
  },
  new: {
    name: "신약성경",
    nameEn: "New Testament",
    bookCount: 27,
    description: "예수 그리스도의 강림부터 새 하늘과 새 땅까지, 약속의 성취와 영원한 구원",
  },
};
